const path = require("path");
const express = require("express");
const { createServer } = require("http");
const { Server } = require("socket.io");
const { gameState } = require("./gameState");
const { primeGameStateFromHistory } = require("./persistence");
const { registerJoinHandlers } = require("./handlers/join");
const { registerMailHandlers } = require("./handlers/mail");
const { registerMaHandlers, scheduleDealRiskLoop } = require("./handlers/ma");
const { registerClientsHandlers, scheduleChurnRiskLoop } = require("./handlers/clients");
const { registerComplianceHandlers } = require("./handlers/compliance");
const { registerHrHandlers } = require("./handlers/hr");
const { registerFinanceHandlers } = require("./handlers/finance");
const { startAiLoop } = require("./ai");
const { startEventLoops } = require("./events");
const { registerAgendaHandlers } = require("./handlers/agenda");
const { registerDocumentsHandlers } = require("./handlers/documents");
const { registerExpensesHandlers } = require("./handlers/expenses");
const { registerGameHandlers } = require("./handlers/game");
const { registerStrategyHandlers, startStrategyLoop } = require("./strategy");
const { registerTaskHandlers, startTaskLoop } = require("./tasks");
const { registerMarketsHandlers, startMarketsLoop } = require("./handlers/markets");
const { registerLiveEventsHandlers, startLiveEventsLoop } = require("./liveEvents");
const { registerDealWorkflowHandlers, startDealWorkflowLoop } = require("./handlers/dealWorkflow");
const { startMarketDayLoop } = require("./marketDay");
const { registerWarRoomHandlers, startWarRoomLoop } = require("./warRoom");
const { registerMercatoHandlers, startMercatoLoop } = require("./mercato");
const { registerCibBonusHandlers } = require("./cibBonus");
const { registerIpoHandlers, startIpoLoop } = require("./ipo");
const { registerTerminalHandlers, startTerminalLoop } = require("./terminal");
const { registerTalentManagementHandlers, startTalentManagementLoop } = require("./talentManagement");
const { registerSocialClimatHandlers, startSocialClimatLoop } = require("./socialClimat");
const { registerComplianceHRHandlers, startComplianceHRLoop } = require("./complianceHR");
const { registerPitchbookHandlers, startPitchbookLoop } = require("./pitchbook");
const { registerStructuredProductsHandlers, startStructuredProductsLoop } = require("./structuredProducts");
const { registerInterbankHandlers, startInterbankLoop } = require("./interbank");
const { registerRiskControlHandlers, startRiskControlLoop } = require("./riskControl");
const { registerRfqHandlers, startRfqLoop } = require("./rfq");
const { registerDataRoomHandlers } = require("./dataRoom");
const { registerNegotiationHandlers, startNegotiationLoop } = require("./negotiation");
const { registerGlobalBankHandlers, startGlobalBankLoop } = require("./globalBank");
const { registerAiAgentsHandlers, startAiAgentsHeartbeat } = require("./aiAgents");
const { registerRivalAggressionHandlers, startRivalAggressionLoops } = require("./rivalAggression");
const { startCentralBankLoop } = require("./centralBank");
const { startRegulatoryStressTestLoop } = require("./regulatoryStressTest");
const { registerPrivateBankingHandlers, startPrivateBankingLoop } = require("./privateBanking");
const { registerAlgoTradingHandlers, startAlgoTradingLoop } = require("./algoTrading");

primeGameStateFromHistory(gameState);

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer);

app.use(express.static(path.join(__dirname, "..", "public")));

io.on("connection", socket => {
  socket.on("ping", () => socket.emit("pong"));
  registerJoinHandlers(io, socket, gameState);
  registerMailHandlers(io, socket, gameState);
  registerMaHandlers(io, socket, gameState);
  registerClientsHandlers(io, socket, gameState);
  registerComplianceHandlers(io, socket, gameState);
  registerHrHandlers(io, socket, gameState);
  registerFinanceHandlers(io, socket, gameState);
  registerAgendaHandlers(io, socket, gameState);
  registerDocumentsHandlers(io, socket, gameState);
  registerExpensesHandlers(io, socket, gameState);
  registerGameHandlers(io, socket, gameState);
  registerStrategyHandlers(io, socket, gameState);
  registerTaskHandlers(io, socket, gameState);
  registerMarketsHandlers(io, socket, gameState);
  registerLiveEventsHandlers(io, socket, gameState);
  registerDealWorkflowHandlers(io, socket, gameState);
  registerWarRoomHandlers(io, socket, gameState);
  registerMercatoHandlers(io, socket, gameState);
  registerCibBonusHandlers(io, socket, gameState);
  registerIpoHandlers(io, socket, gameState);
  registerTerminalHandlers(io, socket, gameState);
  registerTalentManagementHandlers(io, socket, gameState);
  registerSocialClimatHandlers(io, socket, gameState);
  registerComplianceHRHandlers(io, socket, gameState);
  registerPitchbookHandlers(io, socket, gameState);
  registerStructuredProductsHandlers(io, socket, gameState);
  registerInterbankHandlers(io, socket, gameState);
  registerRiskControlHandlers(io, socket, gameState);
  registerRfqHandlers(io, socket, gameState);
  registerDataRoomHandlers(io, socket, gameState);
  registerNegotiationHandlers(io, socket, gameState);
  registerGlobalBankHandlers(io, socket, gameState);
  registerAiAgentsHandlers(io, socket, gameState);
  registerRivalAggressionHandlers(io, socket, gameState);
  registerPrivateBankingHandlers(io, socket, gameState);
  registerAlgoTradingHandlers(io, socket, gameState);
});

startAiLoop(io, gameState);
startEventLoops(io, gameState);
startStrategyLoop(io, gameState);
startTaskLoop(io, gameState);
scheduleDealRiskLoop(io, gameState);
scheduleChurnRiskLoop(io, gameState);
startMarketsLoop(io, gameState);
startLiveEventsLoop(io, gameState);
startDealWorkflowLoop(io, gameState);
startMarketDayLoop(io, gameState);
startWarRoomLoop(io, gameState);
startMercatoLoop(io, gameState);
startIpoLoop(io, gameState);
startTerminalLoop(io, gameState);
startTalentManagementLoop(io, gameState);
startSocialClimatLoop(io, gameState);
startComplianceHRLoop(io, gameState);
startPitchbookLoop(io, gameState);
startStructuredProductsLoop(io, gameState);
startInterbankLoop(io, gameState);
startRiskControlLoop(io, gameState);
startRfqLoop(io, gameState);
startNegotiationLoop(io, gameState);
startGlobalBankLoop(io, gameState);
startAiAgentsHeartbeat(io, gameState);
startRivalAggressionLoops(io, gameState);
startCentralBankLoop(io, gameState);
startRegulatoryStressTestLoop(io, gameState);
startPrivateBankingLoop(io, gameState);
startAlgoTradingLoop(io, gameState);

const PORT = process.env.PORT || 3000;
httpServer.listen(PORT, () => {
  console.log(`Blackwell & Co Multiplayer listening on port ${PORT}`);
});
